# Generated by Django 3.1.7 on 2021-04-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='pred_text',
            field=models.CharField(default='Null', max_length=12),
        ),
        migrations.DeleteModel(
            name='Pred',
        ),
    ]
